DROP DATABASE IF EXISTS project2;
CREATE DATABASE project2;

USE project2;

CREATE TABLE megatable(
	ballot_id INT,
	team_num SMALLINT,
	round_num CHAR(3),
	opp_num SMALLINT,
	side CHAR(1),
	pd SMALLINT,
	ballot__result CHAR(6),
	total_wins TINYINT,
	total_ties TINYINT,
	total_losses TINYINT,
	total_ballots TINYINT,
	record VARCHAR(10),
	total_cs DECIMAL(4,1),
	total_ocs DECIMAL(5,1),
	total_pd SMALLINT,
	team_rank TINYINT,
	team_name VARCHAR(50),
	opp_name VARCHAR(75),
	school VARCHAR(75),
	letter_rank CHAR(1),
	opp_school VARCHAR(75),
	opp_letter_rank CHAR(1),
	tpr_rank VARCHAR(75),
	tpr_points VARCHAR(75),
	tpr_group_designator VARCHAR(75),
	earned_bid VARCHAR(75),
	earned_honorable_mention VARCHAR(75),
	won_spamta VARCHAR(75),
	spamta_honorable_mention VARCHAR(75),
	spamta_ranks VARCHAR(75),
	student_0 VARCHAR(75),
	role_0 VARCHAR(75),
	ranks_0 VARCHAR(75),
	side_0 VARCHAR(75),
	student_1 VARCHAR(75),
	role_1 VARCHAR(75),
	ranks_1 VARCHAR(75),
	side_1 VARCHAR(75),
	student_2 VARCHAR(75),
	role_2 VARCHAR(75),
	ranks_2 VARCHAR(75),
	side_2 VARCHAR(75),
	tournament_name VARCHAR(75),
	division VARCHAR(75),
	start_date VARCHAR(75),
	end_date VARCHAR(75),
	tournament_host VARCHAR(75),
	tournament_level VARCHAR(75),
	tournament_year VARCHAR(75),
	amta_rep_0 VARCHAR(75),
	amta_rep_1 VARCHAR(75),
	tab_note_0 VARCHAR(75),
	tab_note_1 VARCHAR(75),
	tournament_year_1 VARCHAR(75),
	case_name VARCHAR(75),
	full_case VARCHAR(75),
	nationals_case VARCHAR(75),
	case_type VARCHAR(10),
	charge_1 VARCHAR(75),
	charge_2 VARCHAR(150),
	charge_3 VARCHAR(75),
	witness_1_name VARCHAR(20),
	witness_1_type VARCHAR(20),
	witness_1_side VARCHAR(20),
	witness_1_affidavit VARCHAR(110),
	witness_2_name VARCHAR(20),
	witness_2_type VARCHAR(20),
	witness_2_side VARCHAR(20),
	witness_2_affidavit VARCHAR(110),
	witness_3_name VARCHAR(20),
	witness_3_type VARCHAR(20),
	witness_3_side VARCHAR(20),
	witness_3_affidavit VARCHAR(110),
	witness_4_name VARCHAR(20),
	witness_4_type VARCHAR(20),
	witness_4_side VARCHAR(20),
	witness_4_affidavit VARCHAR(110),
	witness_5_name VARCHAR(20),
	witness_5_type VARCHAR(20),
	witness_5_side VARCHAR(20),
	witness_5_affidavit VARCHAR(110),
	witness_6_name VARCHAR(20),
	witness_6_type VARCHAR(20),
	witness_6_side VARCHAR(20),
	witness_6_affidavit VARCHAR(110),
	witness_7_name VARCHAR(20),
	witness_7_type VARCHAR(20),
	witness_7_side VARCHAR(20),
	witness_7_affidavit VARCHAR(110),
	witness_8_name VARCHAR(20),
	witness_8_type VARCHAR(20),
	witness_8_side VARCHAR(20),
	witness_8_affidavit VARCHAR(110),
	witness_9_name VARCHAR(20),
	witness_9_type VARCHAR(20),
	witness_9_side VARCHAR(20),
	witness_9_affidavit VARCHAR(110),
	witness_10_name VARCHAR(20),
	witness_10_type VARCHAR(20),
	witness_10_side VARCHAR(20),
	witness_10_affidavit VARCHAR(110),
	witness_11_name VARCHAR(20),
	witness_11_type VARCHAR(20),
	witness_11_side VARCHAR(20),
	witness_11_affidavit VARCHAR(110),
	witness_12_name VARCHAR(20),
	witness_12_type VARCHAR(20),
	witness_12_side VARCHAR(20),
	witness_12_affidavit VARCHAR(110),
	exhibit_1_name VARCHAR(80),
	exhibit_1_url VARCHAR(134),
	exhibit_2_name VARCHAR(80),
	exhibit_2_url VARCHAR(134),
	exhibit_3_name VARCHAR(80),
	exhibit_3_url VARCHAR(134),
	exhibit_4_name VARCHAR(80),
	exhibit_4_url VARCHAR(134),
	exhibit_5_name VARCHAR(80),
	exhibit_5_url VARCHAR(134),
	exhibit_6_name VARCHAR(80),
	exhibit_6_url VARCHAR(134),
	exhibit_7_name VARCHAR(80),
	exhibit_7_url VARCHAR(134),
	exhibit_8_name VARCHAR(80),
	exhibit_8_url VARCHAR(134),
	exhibit_9_name VARCHAR(134),
	exhibit_9_url VARCHAR(134),
	exhibit_10_name VARCHAR(75),
	exhibit_10_url VARCHAR(134),
	exhibit_11_name VARCHAR(75),
	exhibit_11_url VARCHAR(134),
	exhibit_12_name VARCHAR(75),
	exhibit_12_url VARCHAR(134),
	exhibit_13_name VARCHAR(75),
	exhibit_13_url VARCHAR(134),
	exhibit_14_name VARCHAR(75),
	exhibit_14_url VARCHAR(152),
	exhibit_15_name VARCHAR(75),
	exhibit_15_url VARCHAR(134),
	exhibit_16_name VARCHAR(75),
	exhibit_16_url VARCHAR(134),
	exhibit_17_name VARCHAR(75),
	exhibit_17_url VARCHAR(134),
	exhibit_18_name VARCHAR(75),
	exhibit_18_url VARCHAR(134),
	exhibit_19_name VARCHAR(75),
	exhibit_19_url VARCHAR(134),
	exhibit_20_name VARCHAR(75),
	exhibit_20_url VARCHAR(134),
	exhibit_21_name VARCHAR(75),
	exhibit_21_url VARCHAR(134),
	exhibit_22_name VARCHAR(75),
	exhibit_22_url VARCHAR(134),
	exhibit_23_name VARCHAR(75),
	exhibit_23_url VARCHAR(134),
	exhibit_24_name VARCHAR(75),
	exhibit_24_url VARCHAR(134),
	exhibit_25_name VARCHAR(75),
	exhibit_25_url VARCHAR(134),
	exhibit_26_name VARCHAR(75),
	exhibit_26_url VARCHAR(134),
	exhibit_27_name VARCHAR(75),
	exhibit_27_url VARCHAR(134),
	exhibit_28_name VARCHAR(75),
	exhibit_28_url VARCHAR(134),
	exhibit_29_name VARCHAR(75),
	exhibit_29_url VARCHAR(134),
	exhibit_30_name VARCHAR(75),
	exhibit_30_url VARCHAR(134),
	exhibit_31_name VARCHAR(75),
	exhibit_31_url VARCHAR(134),
	exhibit_32_name CHAR(1),
	exhibit_32_url CHAR(1),
	exhibit_33_name CHAR(1),
	exhibit_33_url CHAR(1),
	exhibit_34_name CHAR(1),
	exhibit_34_url CHAR(1),
	exhibit_35_name CHAR(1),
	exhibit_35_url CHAR(1),
	exhibit_36_name CHAR(1),
	exhibit_36_url CHAR(1),
	exhibit_37_name CHAR(1),
	exhibit_37_url CHAR(1),
	exhibit_38_name CHAR(1),
	exhibit_38_url CHAR(1),
	exhibit_39_name CHAR(1),
	exhibit_39_url CHAR(1),
	exhibit_40_name CHAR(1),
	exhibit_40_url CHAR(1),
	exhibit_41_name CHAR(1),
	exhibit_41_url CHAR(1),
	bid_start_date VARCHAR(75),
	bid_end_date VARCHAR(75),
	bid_location VARCHAR(75),
	tab_note_2 VARCHAR(75),
	student_3 VARCHAR(75),
	role_3 VARCHAR(75),
	ranks_3 VARCHAR(75),
	side_3 VARCHAR(75),
	student_4 VARCHAR(75),
	role_4 VARCHAR(75),
	ranks_4 VARCHAR(75),
	side_4 VARCHAR(75),
	student_5 VARCHAR(75),
	role_5 VARCHAR(75),
	ranks_5 VARCHAR(75),
	side_5 VARCHAR(75),
	tab_note_3 VARCHAR(75),
	location VARCHAR(75),
	ballot_result VARCHAR(75),
	amta_rep_2 VARCHAR(75),
    PRIMARY KEY(ballot_id)
);

LOAD DATA INFILE '~/Google Drive/College Work/Junior/Spring/Databases/full-data.csv'
	IGNORE
	INTO TABLE megatable
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES;


SET SQL_SAFE_UPDATES=0;

DELETE FROM megatable
	WHERE team_num = opp_num; # A team should never be playing itself – this means a team dropped out, so the tab shows them "playing themselves"

DELETE FROM megatable
	WHERE Side = "Δ";
    
SET SQL_SAFE_UPDATES=1;
    
CREATE TABLE IF NOT EXISTS `project2`.`Ballot` (
  ballot_id INT NOT NULL,
  Matchup_tournament_id INT UNSIGNED NOT NULL,
  Matchup_pl_num SMALLINT NOT NULL,
  Matchup_round_num SMALLINT NOT NULL,
  pd SMALLINT NOT NULL,
  ballot_result CHAR(1) NOT NULL,
  PRIMARY KEY (`ballot_id`),
  INDEX `fk_Ballot_Matchup1_idx` (`Matchup_tournament_id` ASC, `Matchup_pl_num` ASC, `Matchup_round_num` ASC))
ENGINE = InnoDB;

INSERT INTO Ballot
	SELECT ballot_id, 1, team_num, ROUND(CAST(round_num AS DECIMAL(2,1))), pd, LEFT(ballot__result, 1)
		FROM megatable; # Need to fix the tournament_id at some point
        
CREATE TABLE IF NOT EXISTS `project2`.`Matchup` (
  `tournament_id` INT UNSIGNED NOT NULL,
  `pl_num` SMALLINT NOT NULL,
  `round_num` SMALLINT NOT NULL,
  `def_num` SMALLINT NOT NULL,
  PRIMARY KEY (`tournament_id`, `pl_num`, `round_num`),
  INDEX `fk_Matchup_Team1_idx` (`tournament_id` ASC, `pl_num` ASC),
  INDEX `fk_Team_team_num_idx` (`def_num` ASC))
ENGINE = InnoDB;

INSERT INTO Matchup
	SELECT DISTINCT 1, team_num, ROUND(CAST(round_num AS DECIMAL(2,1))), opp_num
		FROM megatable;